// Code generated by a template
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PclSharp.Struct;
using PclSharp.Std;
using System.Runtime.CompilerServices;

namespace PclSharp
{
	public static partial class Invoke
	{
		//ctor/dctor
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_xyzi_ctor();
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_xyzi_ctor_indices(IntPtr cloud, IntPtr indices);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_xyzi_ctor_wh(uint width, uint height);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_xyzi_delete(ref IntPtr ptr);
		//methods
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern unsafe PointXYZI* pointcloud_xyzi_at_colrow(IntPtr ptr, int col, int row);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_xyzi_clear(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern unsafe void pointcloud_xyzi_add(IntPtr ptr, PointXYZI* value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_xyzi_downsample(IntPtr ptr, int factor, IntPtr output);
		//properties
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern UIntPtr pointcloud_xyzi_size(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_xyzi_data(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern uint pointcloud_xyzi_width(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_xyzi_width_set(IntPtr ptr, uint width);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern uint pointcloud_xyzi_height(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_xyzi_height_set(IntPtr ptr, uint height);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern IntPtr pointcloud_xyzi_points(IntPtr ptr);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern void pointcloud_xyzi_setIsDense(IntPtr ptr, bool value);
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern bool pointcloud_xyzi_getIsDense(IntPtr ptr);
		[return: MarshalAs(UnmanagedType.Bool)]
		[DllImport(Native.DllName, CallingConvention=Native.CallingConvention)]
		public static extern bool pointcloud_xyzi_isOrganized(IntPtr ptr);
	}

	public unsafe class PointCloudOfXYZI : PointCloud<PointXYZI>
	{
		private bool _suppressDispose;

		public override int Width 
		{
			get { return (int)Invoke.pointcloud_xyzi_width(_ptr); }
			set { Invoke.pointcloud_xyzi_width_set(_ptr, (uint)value); }
		}
		public override int Height 
		{
			get { return (int)Invoke.pointcloud_xyzi_height(_ptr); }
			set { Invoke.pointcloud_xyzi_height_set(_ptr, (uint)value); }
		}
		public override bool IsDense
		{
			get { return Invoke.pointcloud_xyzi_getIsDense(_ptr); }
            set { Invoke.pointcloud_xyzi_setIsDense(_ptr, value); }
		}
		public override int Count => (int)Invoke.pointcloud_xyzi_size(_ptr);
		public int Size => Count;
		public override bool IsOrganized => Invoke.pointcloud_xyzi_isOrganized(_ptr);
		public PointXYZI* Data => (PointXYZI*)Invoke.pointcloud_xyzi_data(_ptr);

		private VectorOfXYZI _points;
		public override Vector<PointXYZI> Points => _points;

		private PointCloudOfXYZI(IntPtr ptr)
		{
			_ptr = ptr;
			_points = new VectorOfXYZI(Invoke.pointcloud_xyzi_points(_ptr));
		}

		internal PointCloudOfXYZI(IntPtr ptr, bool suppressDispose)
			:this(ptr)
		{
			_suppressDispose = suppressDispose;
		}

		public PointCloudOfXYZI() 
			: this(Invoke.pointcloud_xyzi_ctor())
		{
		}

		public PointCloudOfXYZI(int width, int height)
			: this(Invoke.pointcloud_xyzi_ctor_wh((uint)width, (uint)height))
		{
		}

		public PointCloudOfXYZI(PointCloudOfXYZI cloud, Std.VectorOfInt indices)
			:this (Invoke.pointcloud_xyzi_ctor_indices(cloud.Ptr, indices.Ptr))
		{
		}

		public void Downsample(int factor, PointCloud<PointXYZI> output)
			=> Invoke.pointcloud_xyzi_downsample(_ptr, factor, output);

		public override ref PointXYZI At(int col, int row)
			=>  ref Unsafe.AsRef<PointXYZI>(Invoke.pointcloud_xyzi_at_colrow(_ptr, col, row));

		public override void Add(PointXYZI value)
			=> Invoke.pointcloud_xyzi_add(_ptr, &value);

		protected override void DisposeObject()
		{
			if (_suppressDispose)
				return;
			Invoke.pointcloud_xyzi_delete(ref _ptr);
		}
	}
}
