// Code generated by a template
#pragma once
#include "..\export.h"

#include <pcl/pcl_base.h>
#include <pcl/point_types.h>

using namespace pcl;
using namespace std;

typedef boost::shared_ptr<PointCloud<PointXYZI>> boost_cloud;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(void) pclbase_xyzi_setInputCloud(PCLBase<PointXYZI>* ptr, PointCloud<PointXYZI>* cloud)
{
	ptr->setInputCloud(boost_cloud(boost_cloud(), cloud));
}

EXPORT(void) pclbase_xyzi_setIndices(PCLBase<PointXYZI>* ptr, vector<int>* indices)
{
	ptr->setIndices(boost::shared_ptr<vector<int>>(boost::shared_ptr<vector<int>>(), indices));
}

EXPORT(const PointXYZI*) pclbase_xyzi_indexGet(PCLBase<PointXYZI>* ptr, int idx)
{ return &ptr->operator[](idx); }

#ifdef __cplusplus  
}
#endif  
