// Code generated by a template
#pragma once
#include "..\export.h"

#include "pcl\pcl_base.h"
#include "pcl\point_types.h"
#include <pcl/filters/voxel_grid.h>

using namespace pcl;
using namespace std;

typedef VoxelGrid<PointXYZI> voxel_grid;
typedef boost::shared_ptr<PointCloud<PointXYZI>> boost_cloud;

#ifdef __cplusplus
extern "C" {
#endif 

EXPORT(voxel_grid*) filters_voxelGrid_xyzi_ctor()
{
	return new voxel_grid();
}

EXPORT(void) filters_voxelGrid_xyzi_delete(voxel_grid** ptr)
{
	delete *ptr;
	*ptr = NULL;
}

EXPORT(void) filters_voxelGrid_xyzi_filter(VoxelGrid<PointXYZI>* ptr, PointCloud<PointXYZI>* output)
{
	ptr->filter(*output);
}

EXPORT(void) filters_voxelGrid_xyzi_setInputCloud(VoxelGrid<PointXYZI>* ptr, PointCloud<PointXYZI>* cloud)
{
	ptr->setInputCloud(boost_cloud(boost_cloud(), cloud));
}

EXPORT(void) filters_voxelGrid_xyzi_setIndices(VoxelGrid<PointXYZI>* ptr, vector<int>* indices)
{
	ptr->setIndices(boost::shared_ptr<vector<int>>(boost::shared_ptr<vector<int>>(), indices));
}

EXPORT(PointXYZ) filters_voxelGrid_xyzi_getLeafSize(VoxelGrid<PointXYZI>* ptr)
{
	auto size = ptr->getLeafSize();
	return PointXYZ(size[0], size[1], size[2]);
}

EXPORT(void) filters_voxelGrid_xyzi_setLeafSize(VoxelGrid<PointXYZI>* ptr, PointXYZ size)
{
	ptr->setLeafSize(Eigen::Vector4f(size.x, size.y, size.z, 1));
}

EXPORT(void) filters_voxelGrid_xyzi_setFilterFieldName(VoxelGrid<PointXYZI>* ptr, const char* str)
{ ptr->setFilterFieldName(string(str)); }

EXPORT(void) filters_voxelGrid_xyzi_getFilterFieldName(VoxelGrid<PointXYZI>* ptr, char* str, int dstSz)
{ strcpy_s(str, dstSz, ptr->getFilterFieldName().c_str()); }

EXPORT(void) filters_voxelGrid_xyzi_getFilterLimits(VoxelGrid<PointXYZI>* ptr, double* min, double* max)
{ ptr->getFilterLimits(*min, *max); }

EXPORT(void) filters_voxelGrid_xyzi_setFilterLimits(VoxelGrid<PointXYZI>* ptr, double min, double max)
{ ptr->setFilterLimits(min, max); }

EXPORT(void) filters_voxelGrid_xyzi_setDownsampleAllData(VoxelGrid<PointXYZI>* ptr, int value)
{ ptr->setDownsampleAllData(value); }
EXPORT(int) filters_voxelGrid_xyzi_getDownsampleAllData(VoxelGrid<PointXYZI>* ptr)
{ return ptr->getDownsampleAllData(); }

EXPORT(void) filters_voxelGrid_xyzi_setMinimumPointsNumberPerVoxel(VoxelGrid<PointXYZI>* ptr, int value)
{ ptr->setMinimumPointsNumberPerVoxel(value); }
EXPORT(int) filters_voxelGrid_xyzi_getMinimumPointsNumberPerVoxel(VoxelGrid<PointXYZI>* ptr)
{ return ptr->getMinimumPointsNumberPerVoxel(); }

EXPORT(Eigen::Vector3i) filters_voxelGrid_xyzi_getMinBoxCoordinates(VoxelGrid<PointXYZI>* ptr)
{ return ptr->getMinBoxCoordinates(); }

EXPORT(Eigen::Vector3i) filters_voxelGrid_xyzi_getMaxBoxCoordinates(VoxelGrid<PointXYZI>* ptr)
{ return ptr->getMaxBoxCoordinates(); }

EXPORT(Eigen::Vector3i) filters_voxelGrid_xyzi_getNrDivisions(VoxelGrid<PointXYZI>* ptr)
{ return ptr->getNrDivisions(); }

EXPORT(Eigen::Vector3i) filters_voxelGrid_xyzi_getDivisionMultiplier(VoxelGrid<PointXYZI>* ptr)
{ return ptr->getDivisionMultiplier(); }

#ifdef __cplusplus  
}
#endif  
